<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-3SJ6CNC" failures="1" tests="5" name="Personal loan" time="0.097" errors="0" timestamp="2023-03-21T13:30:06 CET">
  <testcase classname="testing.Day1" name="Demo" time="0.013">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testing.Day1.Demo(Day1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="testing.Day2" name="ploan" time="0.002"/>
  <testcase classname="testing.Day4" name="LoginAPIHomeLoan" time="0.005"/>
  <testcase classname="testing.Day4" name="MobileLoginHomeLoan" time="0.002"/>
  <testcase classname="testing.Day4" name="WebloginHomeLoan" time="0.005"/>
  <testcase classname="testing.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
